### ISSUE TITLE
KXG60ZNV1T02

### ISSUE THREAD

**Issue by marsuss** [Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh#7]
Hi, how did you make this ssd work (KXG60ZNV1T02) under macOS?

**Comment by VGerris** [comment]
Hi, check if it is supported and : https://www.tonymacx86.com/threads/choosing-a-compatible-nvme-ssd-for-your-macos-boot-drive.323479/ . If his works and yours not, check for a firmware update. Whether or not the drive works in this case should only depend on the drive.

**Comment by marsuss** [comment]
Hi, thank you very much for your help. SSD now works without any problems on Ventura and Sonoma as well : )

**Comment by VGerris** [comment]
Great, please share how, if you did anything? Good for others. Please close when solved ')

**Comment by marsuss** [comment]
Well, that's funny but I did absolutely nothing just works now, without any kexts, patches, etc...
